# Generated by Django 3.2.6 on 2021-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name should be max. of 40 characters', max_length=40)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name should be max. of 40 characters', max_length=40)),
                ('last_name', models.CharField(help_text='Last name should be max. of 40 characters', max_length=40)),
                ('permanent_address', models.CharField(help_text=' Permanent Address should be max. of 50 characters', max_length=50)),
                ('temporary_address', models.CharField(help_text=' Temporary Address should be max. of 50 characters', max_length=50)),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile no. should be max. of 15 characters', max_length=15)),
                ('email_id', models.CharField(blank=True, help_text='Email Id should be max. of 50 characters', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
